# Generated by Django 3.1.2 on 2020-10-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='duration',
            new_name='duration_in_minutes',
        ),
    ]
